public enum MessageType {
    PHASE_ONE_VALUE,
    PHASE_TWO_VALUE,
    LEADER_VALUE,
    FAULT_PHASE_ONE_VALUE,
    FAULT_PHASE_TWO_VALUE,
    FAULT_LEADER_VALUE,
    ALGORITHM,
    IS_FAULTY,
    FAULTY_SET,
    FINAL_VALUE,
    CLIENT_REQUEST
}