public enum MessageType {
    VALUE,
    FAULT_VALUE,
    ALGORITHM,
    IS_FAULTY,
    FAULTY_NODE,
    FAULTY_SET,
    FINAL_VALUE,
    CLIENT_REQUEST,
    LEADER_VALUE,
    FINALIZE_ROUND,
    START_ROUND
}